#Configuración general
server:
  port: 8020
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: escoz-pi-status
  profiles:
    active: dev

  # Configuración de la BB DD
  datasource:
    url: # Ver perfil
    username: # Ver perfil
    password: # Ver perfil
    driver-class-name: # Ver perfil
  jpa:
    hibernate:
      ddl-auto: # Ver perfil